### PR TITLE
chore: add benchmark workflow

### LINKED ISSUE #7: add or use an existing benchmark workflow
ghtml should be benchmarked against other libraries like kita/html

### PR DESCRIPTION
**Pull request by gurgunday**
WIP

Will close #7

### CODE REVIEW

**Comment by gurgunday** [comment]
This results in a degradation in performance, possibly because of JITed version being slower

**Comment by danielweck** [comment]
hello :) 
have you compared performance with htm?
https://github.com/developit/htm



screenshot from:

https://twitter.com/gurgundayX/status/1775977621873959334

**Comment by gurgunday** [comment]
> have you compared performance with htm?

Hi, I haven't yet, but I will now :)

Maybe we can add it to Kitajs' benchmarks and pull from there

**Comment by gurgunday** [comment]
Benchmark Results:
```json
[
```

**Pull request merged**
