### PR TITLE
feat(pkg): add typescript support

### PR DESCRIPTION
**Pull request by douglasduteil**
<p align="center">
    
</p>

### CODE REVIEW

**Comment by gurgunday** [comment]
Haha, sure!

Just wondering, is TS complaining about [JSDoc](https://github.com/gurgunday/ghtml/blob/09ed967f836d1ae8b488be91f81e9d3a8f1a6312/src/html.js#L41-L45) not being enough?

**Comment by douglasduteil** [comment]
I mean using the existing 
https://github.com/gurgunday/ghtml/blob/09ed967f836d1ae8b488be91f81e9d3a8f1a6312/src/html.js#L41-L46
as type definition ?

I tried 

```js 
// in ghtml/package.json
{
  // [...]
  "type": "module",
  "bin": "./bin/src/index.js",
  "main": "./src/index.js",
  "types": "./src/index.js",
  // [...]
} 
```

And TypeScript said no

```
Could not find a declaration file for module 'ghtml'. '/home/x/y/z/node_modules/ghtml/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ghtml` if it exists or add a new declaration (.d.ts) file containing `declare module 'ghtml';`ts(7016)
```

A tiny `.d.ts` file seems to be required

**Comment by gurgunday** [comment]
Hey,

Thanks for the PR and issue description!

To automate as much as possible, I added TS support in a bit different way, but I made sure to [add you as a co-author to the commit](https://github.com/gurgunday/ghtml/commit/0da36e55f0251f95b4f8afc9ce4dceb6a711322c)

Thanks again!

---

Closed by 0da36e55f0251f95b4f8afc9ce4dceb6a711322c

**Comment by douglasduteil** [comment]
<h1> <p align="center">:tada:  Beautiful :tada: </p></h1>


<p align="center">
    
</p>

**Pull request closed without merging**
